

const app = {
    name: "",
    brand: {
        title: "NBK",
        description: "Generated by create next app",
        keywords: "",

    }

};

const services: Type.Service[] = [
    {
        id: "1",
        title: "renovation",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: "/images/services/serv-image-1.jpeg"
    },
    {
        id: "2",
        title: "architecture",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: "/images/services/serv-image-2.jpeg"
    },
    {
        id: "3",
        title: "construction",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: "/images/services/serv-image.jpeg"
    }
];
const works: Type.Work[] = [
    {
        id: "1",
        slug: "donec-rhoncus",
        title: "Donec mide",
        description: "Landscaping",
        image: "/images/work-1.jpeg",
        options: [
            {label: "Project Type", value: "Painting"},
            {label: "Client", value: "halildogan"},
            {label: "Completion Date", value: "March 2007"},
            {label: "Project Size", value: "3350 Square Feet"},
            {label: "Contract Value", value: "$720.000"},
            {label: "Location", value: "Brooklyn, NY"},
        ],
        text: `<div>
            <div className="w-richtext">
                <h3>Intro</h3>
                <p>Usually, the sites of institutions that provide financial services are full of information. Our goal was to provide the maximum of information to potential customers of Webflow, but to do it in a stylish and modern way. <br />
                    <br />Minimalism combined with elements of french typography and brutalism helped us to realize the site exactly as we imagined with the client at the beginning: visually restrained, but stylish. Informative and pleasant to use, with an elegant aftertaste of a serious financial institution.
                </p>
            </div>
        </div>
        <div className="margin-20px">
            <div className="w-richtext">
            <h3>Quality</h3>
            <p>Usually, the sites of institutions that provide financial services are full of information. Our goal was to provide the maximum of information to potential customers of Webflow, but to do it in a stylish and modern way. <br />
                <br />Minimalism combined with elements of french typography and brutalism helped us to realize the site exactly as we imagined with the client at the beginning: visually restrained, but stylish. Informative and pleasant to use, with an elegant aftertaste of a serious financial institution.
            </p>
            <p>The sites of institutions that provide financial services are full of information. Our goal was to provide the maximum of information to potential customers of Webflow, but to do it in a stylish and modern way.</p>
            <p>‍ <br />Combined with elements of french typography and brutalism helped us to realize the site exactly as we imagined with the client at the beginning: visually restrained, but stylish. Informative and pleasant to use, with an elegant aftertaste of a serious financial institution. </p>
            </div>
        </div>`
    },
    {
        id: "2",
        slug: "etiam-rutrum",
        title: "Quisque rutrum",
        description: "Renovation",
        image: "/images/work-3.jpeg",
        options: [
            {label: "Project Type", value: "Painting"},
            {label: "Client", value: "halildogan"},
            {label: "Completion Date", value: "March 2007"},
            {label: "Project Size", value: "3350 Square Feet"},
            {label: "Contract Value", value: "$720.000"},
            {label: "Location", value: "Brooklyn, NY"},
        ]
    },
    {
        id: "3",
        slug: "etiam-rhoncus",
        title: "Etiam rhoncus",
        description: "Painting",
        image: "/images/work-2.jpeg",
        options: [
            {label: "Project Type", value: "Painting"},
            {label: "Client", value: "halildogan"},
            {label: "Completion Date", value: "March 2007"},
            {label: "Project Size", value: "3350 Square Feet"},
            {label: "Contract Value", value: "$720.000"},
            {label: "Location", value: "Brooklyn, NY"},
        ]
    },
    {
        id: "4",
        slug: "etiam-magna",
        title: "Proin magna",
        description: "Gardening",
        image: "/images/work-4.jpeg",
        options: [
            {label: "Project Type", value: "Painting"},
            {label: "Client", value: "halildogan"},
            {label: "Completion Date", value: "March 2007"},
            {label: "Project Size", value: "3350 Square Feet"},
            {label: "Contract Value", value: "$720.000"},
            {label: "Location", value: "Brooklyn, NY"},
        ]
    }
];

const valuesItems: Type.ValueItem[] = [
    {
      id: "1",
      icon: "/images/icons/1.png",
      title: "10 years experience",
      description: "Our aim is to continuously exceed the expectations of our client to deliver quality construction."
    },{
      id: "2",
      icon: "/images/icons/2.png",
      title: "best materials",
      description: "Our partnership with our clients is based on mutual trust and we do what is best for."
    },{
      id: "3",
      icon: "/images/icons/3.png",
      title: "professional standards",
      description: "To become an industry leader, it is important for us to encourage team work."
    },
];

const posts: Type.Post[] = [
    {
        id: "1",
        title: "Flexible office space in commercial offices",
        slug: `flexible-office-space-in-commercial-offices`,
        description: "",
        category: "Branding",
        image: "/images/blog-1.jpeg",
        created: "December 4, 2019",
        text: `<h3>First impressions</h3>
        <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Curabitur ullamcorper ultricies nisi. Nam eget dui.</p>
        <p>Aenean viverra rhoncus pede. Phasellus volutpat, metus eget egestas mollis, lacus lacus blandit dui, id egestas quam mauris ut lacus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Suspendisse potenti. In turpis.</p>
        <p>Praesent congue erat at massa. Aenean massa. Sed cursus turpis vitae tortor. Cras non dolor. Suspendisse enim turpis, dictum sed iaculis condimentum nec nisi.</p>
        <h3>Second impressions</h3>
        <p>Cras sagittis. Nam at tortor in tellus interdum sagittis. Vivamus quis mi. Etiam rhoncus. Sed a libero.</p>
        <p>Pellentesque egestas, neque sit amet convallis pulvinar, justo nulla eleifend augue, ac auctor orci leo non est. Nam pretium turpis et arcu. Phasellus nec sem in justo pellentesque facilisis. Sed libero. Aliquam lobortis.</p>
        <p>‍</p>
        <blockquote>“User engagement and experience has become a major focus for any web-based service in recent years”</blockquote>
        <p>‍</p>
        <h3>A perfect fit</h3>
        <p>Praesent nonummy mi in odio. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Nulla porta dolor. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. In hac habitasse platea dictumst.</p>
        <p>Praesent ac massa at ligula laoreet iaculis. Etiam ultricies nisi vel augue. Quisque malesuada placerat nisl. Nulla neque dolor, sagittis eget, iaculis quis, molestie non, velit. Duis lobortis massa imperdiet quam. <br />‍ </p>
        <h3>Quality</h3>
        <p>Suspendisse feugiat. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Sed libero. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
        <p>Nunc sed turpis. Vestibulum rutrum, mi nec elementum vehicula, eros quam gravida nisl, id fringilla neque ante vel mi. Proin pretium, leo ac pellentesque mollis, felis nunc ultrices eros, sed gravida augue augue mollis justo. Curabitur turpis. Nam at tortor in tellus interdum sagittis.</p>
        <p>Proin pretium, leo ac pellentesque mollis, felis nunc ultrices eros, sed gravida augue augue mollis justo. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Proin magna. Curabitur a felis in nunc fringilla tristique. Curabitur suscipit suscipit tellus.</p>`
    },
    {
        id: "2",
        title: "Why green spaces are the future in word",
        slug: `why-green-spaces-are-the-future-in-word`,
        description: "",
        category: "Inspiration",
        image: "/images/blog-2.jpeg",
        created: "February 10, 2020",
        text: `<h3>First impressions</h3>
        <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Donec mi odio, faucibus at, scelerisque quis, convallis in, nisi. Curabitur ullamcorper ultricies nisi. Nam eget dui.</p>
        <p>Aenean viverra rhoncus pede. Phasellus volutpat, metus eget egestas mollis, lacus lacus blandit dui, id egestas quam mauris ut lacus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Suspendisse potenti. In turpis.</p>
        <p>Praesent congue erat at massa. Aenean massa. Sed cursus turpis vitae tortor. Cras non dolor. Suspendisse enim turpis, dictum sed iaculis condimentum nec nisi.</p>
        <h3>Second impressions</h3>
        <p>Cras sagittis. Nam at tortor in tellus interdum sagittis. Vivamus quis mi. Etiam rhoncus. Sed a libero.</p>
        <p>Pellentesque egestas, neque sit amet convallis pulvinar, justo nulla eleifend augue, ac auctor orci leo non est. Nam pretium turpis et arcu. Phasellus nec sem in justo pellentesque facilisis. Sed libero. Aliquam lobortis.</p>
        <p>‍</p>
        <blockquote>“User engagement and experience has become a major focus for any web-based service in recent years”</blockquote>
        <p>‍</p>
        <h3>A perfect fit</h3>
        <p>Praesent nonummy mi in odio. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Nulla porta dolor. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. In hac habitasse platea dictumst.</p>
        <p>Praesent ac massa at ligula laoreet iaculis. Etiam ultricies nisi vel augue. Quisque malesuada placerat nisl. Nulla neque dolor, sagittis eget, iaculis quis, molestie non, velit. Duis lobortis massa imperdiet quam. <br />‍ </p>
        <h3>Quality</h3>
        <p>Suspendisse feugiat. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Sed libero. In hac habitasse platea dictumst. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
        <p>Nunc sed turpis. Vestibulum rutrum, mi nec elementum vehicula, eros quam gravida nisl, id fringilla neque ante vel mi. Proin pretium, leo ac pellentesque mollis, felis nunc ultrices eros, sed gravida augue augue mollis justo. Curabitur turpis. Nam at tortor in tellus interdum sagittis.</p>
        <p>Proin pretium, leo ac pellentesque mollis, felis nunc ultrices eros, sed gravida augue augue mollis justo. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Proin magna. Curabitur a felis in nunc fringilla tristique. Curabitur suscipit suscipit tellus.</p>`
    },
    {
        id: "2",
        title: "NY young architects you should be following",
        slug: `inspiring-new-york-young-architects-you-should-be-following`,
        description: "",
        category: "Design",
        image: "/images/blog-3.jpeg",
        created: "April 30, 2020"
    }
]

export {
    app, services, works, valuesItems, posts
}