

const app = {
    name: "",
    brand: {
        title: "NBK",
        description: "Generated by create next app",
        keywords: "",

    }

};

const services: Type.Service[] = [
    {
        id: "1",
        title: "renovation",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: "/images/services/serv-image-1.jpeg"
    },
    {
        id: "2",
        title: "architecture",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: "/images/services/serv-image-2.jpeg"
    },
    {
        id: "3",
        title: "construction",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: "/images/services/serv-image.jpeg"
    }
];
const works: Type.Work[] = [
    {
        id: "1",
        slug: "donec-rhoncus",
        title: "Donec mide",
        description: "Landscaping",
        image: "/images/work-1.jpeg",
        options: [
            {label: "Project Type", value: "Painting"},
            {label: "Client", value: "halildogan"},
            {label: "Completion Date", value: "March 2007"},
            {label: "Project Size", value: "3350 Square Feet"},
            {label: "Contract Value", value: "$720.000"},
            {label: "Location", value: "Brooklyn, NY"},
        ],
        text: `<div>
            <div className="w-richtext">
                <h3>Intro</h3>
                <p>Usually, the sites of institutions that provide financial services are full of information. Our goal was to provide the maximum of information to potential customers of Webflow, but to do it in a stylish and modern way. <br />
                    <br />Minimalism combined with elements of french typography and brutalism helped us to realize the site exactly as we imagined with the client at the beginning: visually restrained, but stylish. Informative and pleasant to use, with an elegant aftertaste of a serious financial institution.
                </p>
            </div>
        </div>
        <div className="margin-20px">
            <div className="w-richtext">
            <h3>Quality</h3>
            <p>Usually, the sites of institutions that provide financial services are full of information. Our goal was to provide the maximum of information to potential customers of Webflow, but to do it in a stylish and modern way. <br />
                <br />Minimalism combined with elements of french typography and brutalism helped us to realize the site exactly as we imagined with the client at the beginning: visually restrained, but stylish. Informative and pleasant to use, with an elegant aftertaste of a serious financial institution.
            </p>
            <p>The sites of institutions that provide financial services are full of information. Our goal was to provide the maximum of information to potential customers of Webflow, but to do it in a stylish and modern way.</p>
            <p>‍ <br />Combined with elements of french typography and brutalism helped us to realize the site exactly as we imagined with the client at the beginning: visually restrained, but stylish. Informative and pleasant to use, with an elegant aftertaste of a serious financial institution. </p>
            </div>
        </div>`
    },
    {
        id: "2",
        slug: "etiam-rutrum",
        title: "Quisque rutrum",
        description: "Renovation",
        image: "/images/work-3.jpeg",
        options: [
            {label: "Project Type", value: "Painting"},
            {label: "Client", value: "halildogan"},
            {label: "Completion Date", value: "March 2007"},
            {label: "Project Size", value: "3350 Square Feet"},
            {label: "Contract Value", value: "$720.000"},
            {label: "Location", value: "Brooklyn, NY"},
        ]
    },
    {
        id: "3",
        slug: "etiam-rhoncus",
        title: "Etiam rhoncus",
        description: "Painting",
        image: "/images/work-2.jpeg",
        options: [
            {label: "Project Type", value: "Painting"},
            {label: "Client", value: "halildogan"},
            {label: "Completion Date", value: "March 2007"},
            {label: "Project Size", value: "3350 Square Feet"},
            {label: "Contract Value", value: "$720.000"},
            {label: "Location", value: "Brooklyn, NY"},
        ]
    },
    {
        id: "4",
        slug: "etiam-magna",
        title: "Proin magna",
        description: "Gardening",
        image: "/images/work-4.jpeg",
        options: [
            {label: "Project Type", value: "Painting"},
            {label: "Client", value: "halildogan"},
            {label: "Completion Date", value: "March 2007"},
            {label: "Project Size", value: "3350 Square Feet"},
            {label: "Contract Value", value: "$720.000"},
            {label: "Location", value: "Brooklyn, NY"},
        ]
    }
];

const valuesItems: Type.ValueItem[] = [
    {
      id: "1",
      icon: "/images/icons/1.png",
      title: "10 years experience",
      description: "Our aim is to continuously exceed the expectations of our client to deliver quality construction."
    },{
      id: "2",
      icon: "/images/icons/2.png",
      title: "best materials",
      description: "Our partnership with our clients is based on mutual trust and we do what is best for."
    },{
      id: "3",
      icon: "/images/icons/3.png",
      title: "professional standards",
      description: "To become an industry leader, it is important for us to encourage team work."
    },
];

export {
    app, services, works, valuesItems
}